### ISSUE TITLE
Cannot Sign in with Microsoft Account

### ISSUE THREAD

**Issue by ardhagp** [PurpleSoftSrl/azure_devops_app#6]
After updating to latest version,  i cannot sign in with microsoft account.

Clear all cache or reinstalling the app didn't help.

https://github.com/PurpleSoftSrl/azure_devops_app/assets/1522377/ff5e5585-114b-4c17-bf00-0acf4f28465d

**Comment by sstasi95** [comment]
Hi, which device/OS are you running the app on? Do you have Microsoft Authenticator app installed?

**Comment by joseederangojr** [comment]
Same issue on iPhone 12 v16.6.1

**Comment by ardhagp** [comment]
> Hi, which device/OS are you running the app on? Do you have Microsoft Authenticator app installed?

hi,
this issue occured in red mi note 12 / android 13 and yes, i have microsoft authenticator installed.

**Comment by sstasi95** [comment]
@ardhagp unfortunately I'm not able to reproduce it. I don't have a redmi, but I tested it on a samsung galaxy A13 running android 13, and I was able to sign in both with and without the authenticator app installed. I've just added some error logs so that in the next release I'll have more information to understand the issue.

In the meantime, I suggest you to sign out from your Microsoft account and retry.

**Comment by pless84** [comment]
Can confirm same issue on Google Pixel 7/Android 14

**Comment by michalhainc** [comment]
Same issue here on Poco F1 Android 11

**Comment by Saiful-Islam-Sakib** [comment]
Same issue in OnePlus 8

**Comment by Saiful-Islam-Sakib** [comment]
Working as expected.
Thank you so much.
